/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import CapaDatos.RegistroLogin;
import CapaDatos.ConexionCliente;
import CapaDatos.RegistroMuebles;
import CapaDatos.RegistroFactura;
import CapaNegocio.Login;
import CapaNegocio.Cliente;
import CapaNegocio.Mueble;
import CapaNegocio.Factura;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author claus
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    public InterfazGrafica() {
        initComponents();
        
        pnlLogin.setBounds(100,100,360,226);
        pnlDatosCliente.setVisible(false);
        pnlProducto.setVisible(false);
        pnlEntrega.setVisible(false);
        pnlFactura.setVisible(false);
        pnlProceso.setVisible(false);
        ifAyuda.setVisible(false);
        jMenu1.setEnabled(false);
        jMenu2.setEnabled(false);
        jMenu3.setEnabled(true);
        
        
        RegistroLogin.cargarUsuarios();
       
        RegistroLogin.cargarUsuarios();
        
        //PRECIOS DE PRODUCTOS
        tblPrecios.setValueAt("Silla", 0,0);
        tblPrecios.setValueAt(50000, 0,1);
        
        tblPrecios.setValueAt("Mesa", 1,0);
        tblPrecios.setValueAt(200000, 1,1);
        
        tblPrecios.setValueAt("Sillón", 2,0);
        tblPrecios.setValueAt(300000, 2,1);
        
        tblPrecios.setValueAt("Estante", 3,0);
        tblPrecios.setValueAt(250000, 3,1);
    }
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosCliente2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtVendedor7 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtNumeroCliente2 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtEmail2 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        btnInsertar2 = new javax.swing.JButton();
        btnActualizar2 = new javax.swing.JButton();
        btnLimpiar2 = new javax.swing.JButton();
        btnListar2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaClientes2 = new javax.swing.JTextArea();
        btnEliminar2 = new javax.swing.JButton();
        btnInsertar8 = new javax.swing.JButton();
        btnActualizar5 = new javax.swing.JButton();
        btnEliminar5 = new javax.swing.JButton();
        btnLimpiar5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDatosCliente = new javax.swing.JMenuItem();
        mniOrden = new javax.swing.JMenuItem();
        mniOrden1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniProceso = new javax.swing.JMenuItem();
        mniProceso1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        pnlDatosCliente2.setBackground(new java.awt.Color(255, 204, 102));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel11.setText("NOMBRE COMPLETO");

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel22.setText("NUMERO CLIENTE");

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("DATOS CLIENTE");

        jLabel70.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(102, 102, 102));
        jLabel70.setText("LISTA CLIENTES");

        jLabel47.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel47.setText("VENDEDOR:");

        txtVendedor7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel48.setText("EMAIL");

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        btnInsertar2.setText("Insertar");
        btnInsertar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar2ActionPerformed(evt);
            }
        });

        btnActualizar2.setText("Actualizar");
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });

        btnLimpiar2.setText("Limpiar");
        btnLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar2ActionPerformed(evt);
            }
        });

        btnListar2.setText("Listar");
        btnListar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar2ActionPerformed(evt);
            }
        });

        txaClientes2.setColumns(20);
        txaClientes2.setRows(5);
        jScrollPane6.setViewportView(txaClientes2);

        btnEliminar2.setText("Eliminar");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosCliente2Layout = new javax.swing.GroupLayout(pnlDatosCliente2);
        pnlDatosCliente2.setLayout(pnlDatosCliente2Layout);
        pnlDatosCliente2Layout.setHorizontalGroup(
            pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                        .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCliente2Layout.createSequentialGroup()
                                .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addComponent(btnLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCliente2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(27, 27, 27))
                                    .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                                        .addComponent(jLabel48)
                                        .addGap(22, 22, 22)))
                                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombre2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosCliente2Layout.createSequentialGroup()
                                        .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar2))
                                    .addComponent(txtNumeroCliente2, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel70)
                                    .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(txtVendedor7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListar2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47)))))
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosCliente2Layout.setVerticalGroup(
            pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel70))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumeroCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar2))
                        .addGap(30, 30, 30)
                        .addComponent(btnInsertar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListar2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCliente2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(txtVendedor7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosCliente2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47)
                            .addComponent(btnLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertar8.setText("Renovar");
        btnInsertar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar8ActionPerformed(evt);
            }
        });

        btnActualizar5.setText("Actualizar");
        btnActualizar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar5ActionPerformed(evt);
            }
        });

        btnEliminar5.setText("Eliminar");
        btnEliminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar5ActionPerformed(evt);
            }
        });

        btnLimpiar5.setText("Limpiar");
        btnLimpiar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar5ActionPerformed(evt);
            }
        });

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(255, 204, 102));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Tareas Funcionario");
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        mniDatosCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniDatosCliente.setText("Préstamos");
        mniDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatosClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mniDatosCliente);

        mniOrden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniOrden.setText("Devolución y Multas");
        mniOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOrdenActionPerformed(evt);
            }
        });
        jMenu1.add(mniOrden);

        mniOrden1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniOrden1.setText("Materiales");
        mniOrden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOrden1ActionPerformed(evt);
            }
        });
        jMenu1.add(mniOrden1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Tareas Adminstrador");
        jMenu2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mniProceso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniProceso.setText("Registrar Usuarios");
        mniProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProcesoActionPerformed(evt);
            }
        });
        jMenu2.add(mniProceso);

        mniProceso1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniProceso1.setText("Registros Generales");
        mniProceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProceso1ActionPerformed(evt);
            }
        });
        jMenu2.add(mniProceso1);

        jMenuBar1.add(jMenu2);

        jMenu5.setForeground(new java.awt.Color(51, 51, 51));
        jMenu5.setText("SALIR");
        jMenu5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        mnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnSalir.setText("CERRAR APLICACION");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu5.add(mnSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1749, 1749, 1749)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar5, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                    .addComponent(btnEliminar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(624, 624, 624)
                .addComponent(btnInsertar8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void btnInsertar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertar2ActionPerformed

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar2ActionPerformed

    private void btnLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiar2ActionPerformed

    private void btnListar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListar2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void btnActualizar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar5ActionPerformed

    private void btnLimpiar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiar5ActionPerformed

    private void btnEliminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar5ActionPerformed

    private void btnInsertar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertar8ActionPerformed

    private void mniDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatosClienteActionPerformed
        // TODO add your handling code here:

        pnlDatosCliente.setVisible(true);
        pnlProducto.setVisible(false);
        pnlProceso.setVisible(false);
        pnlFactura.setVisible(false);
        pnlEntrega.setVisible(false);
        ifAyuda.setVisible(false);

    }//GEN-LAST:event_mniDatosClienteActionPerformed

    private void mniOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOrdenActionPerformed
        // TODO add your handling code here:
        pnlDatosCliente.setVisible(false);
        pnlProducto.setVisible(true);
        pnlProceso.setVisible(false);
        pnlFactura.setVisible(false);
        pnlEntrega.setVisible(false);
        ifAyuda.setVisible(false);
    }//GEN-LAST:event_mniOrdenActionPerformed

    private void mniOrden1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOrden1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniOrden1ActionPerformed

    private void mniProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProcesoActionPerformed
        // TODO add your handling code here:
        pnlDatosCliente.setVisible(false);
        pnlProducto.setVisible(false);
        pnlProceso.setVisible(true);
        pnlFactura.setVisible(false);
        pnlEntrega.setVisible(false);
        ifAyuda.setVisible(false);
    }//GEN-LAST:event_mniProcesoActionPerformed

    private void mniProceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProceso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniProceso1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    public void limpiarControles()
    {
      txtNumeroCliente.setText("");
      txtNombre.setText("");
      txtEmail.setText("");
      txaClientes.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JButton btnActualizar5;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminar5;
    private javax.swing.JButton btnInsertar2;
    private javax.swing.JButton btnInsertar8;
    private javax.swing.JButton btnLimpiar2;
    private javax.swing.JButton btnLimpiar5;
    private javax.swing.JButton btnListar2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mniDatosCliente;
    private javax.swing.JMenuItem mniOrden;
    private javax.swing.JMenuItem mniOrden1;
    private javax.swing.JMenuItem mniProceso;
    private javax.swing.JMenuItem mniProceso1;
    private javax.swing.JPanel pnlDatosCliente2;
    private javax.swing.JTextArea txaClientes2;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNumeroCliente2;
    private javax.swing.JLabel txtVendedor7;
    // End of variables declaration//GEN-END:variables
}
